import axios from "axios"
import { API_URL } from "../../config/api"
import {CREATE_RESTAURANT_REQUEST,
    CREATE_RESTAURANT_SUCCESS,
    CREATE_RESTAURANT_FAILURE,
    GET_ALL_RESTAURANTS_REQUEST,
    GET_ALL_RESTAURANTS_SUCCESS,
    GET_ALL_RESTAURANTS_FAILURE,
    DELETE_RESTAURANT_REQUEST,
    DELETE_RESTAURANT_SUCCESS,
    DELETE_RESTAURANT_FAILURE,
    UPDATE_RESTAURANT_REQUEST,
    UPDATE_RESTAURANT_SUCCESS,
    UPDATE_RESTAURANT_FAILURE,
    GET_RESTAURANT_BY_ID_REQUEST,
    GET_RESTAURANT_BY_ID_SUCCESS,
    GET_RESTAURANT_BY_ID_FAILURE,
    GET_RESTAURANT_BY_USER_ID_REQUEST,
GET_RESTAURANT_BY_USER_ID_SUCCESS,
GET_RESTAURANT_BY_USER_ID_FAILURE,
UPDATE_RESTAURANT_STATUS_REQUEST,
UPDATE_RESTAURANT_STATUS_SUCCESS,
UPDATE_RESTAURANT_STATUS_FAILURE,
CREATE_EVENTS_REQUEST,
CREATE_EVENTS_SUCCESS,
CREATE_EVENTS_FAILURE,
GET_ALL_EVENTS_REQUEST,
GET_ALL_EVENTS_SUCCESS,
GET_ALL_EVENTS_FAILURE,
DELETE_EVENTS_REQUEST,
DELETE_EVENTS_SUCCESS,
DELETE_EVENTS_FAILURE,
GET_RESTAIRANTS_EVENTS_REQUEST,
GET_RESTAIRANTS_EVENTS_SUCCESS,
GET_RESTAIRANTS_EVENTS_FAILURE,
CREATE_CATEGORY_REQUEST,
CREATE_CATEGORY_SUCCESS,
CREATE_CATEGORY_FAILURE,
GET_RESTAURANTS_CATEGORY_REQUEST,
GET_RESTAURANTS_CATEGORY_SUCCESS,
GET_RESTAURANTS_CATEGORY_FAILURE,

} from "./ActionType"



export const Get_all_restaurents = () => async(dispatch)=>{
    dispatch({type:GET_ALL_RESTAURANTS_REQUEST})
    try {
        const {data} = await axios.get(`${API_URL}/api/restaurants/allRestaurants`)
        dispatch({type:GET_ALL_RESTAURANTS_SUCCESS, payload:data})
        console.log("Restaurant", data)
    } catch (error) {
        dispatch({type:GET_ALL_RESTAURANTS_FAILURE, payload:error.response?.data || error.message})
        console.log("error", error)
    }
}